### PR TITLE
Adding account_id as a parameter for exchangeToken()

### PR DESCRIPTION
**Pull request by joshstrange**

### CODE REVIEW

**Comment by joshstrange** [comment]
Well now I'm just confused... Plaid seems to say you need to have the account_id but I'm not getting one back from their library like their docs say I should and trying to pass anything as the account_id causes the endpoint to fail...

**Comment by travoltron** [comment]
The account_id param is only passed if you're updating the credentials of
an account linked through the Link product. It's optional for purposes of
that request.

On Thu, Jun 16, 2016 at 2:47 PM, Josh Strange <notifications@github.com>
wrote:

> Closed #2 <https://github.com/travoltron/plaid/pull/2>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/travoltron/plaid/pull/2#event-695053417>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AChkMljl8OWM8dgjcMsmF74dHnMLj2Kgks5qMZo6gaJpZM4I3qxc>
> .
>



-- 
Ben Warburton

**Comment by joshstrange** [comment]
Ahh, ok, that makes a little more sense

**Comment by travoltron** [comment]
Version bump: added that as a default null option on that endpoint

**Comment by joshstrange** [comment]
@travoltron So I think this endpoint will have the same issue as search(). If you pass a null the API endpoint is not happy. Probably need to do a similar thing where you unset it from the body if it's null. Incoming pull request.

**Pull request closed without merging**
