### PR TITLE
Cleaning up config values and fixing search

### PR DESCRIPTION
**Pull request by joshstrange**
Just a couple of issues we ran into cleaned up:

* Config values were not consistent client_id vs client-id, I standardized on client_id as it's what is in the config file. The current workaround is to set both client_id and client-id in config

* Fixing search which previously would not return anything if you just passed a query. Now it doesn't pass the products (p) key up if it's null. The current workaround is to pass up all products.

### CODE REVIEW

**Comment by joshstrange** [comment]
Also adding in changing of readme for adding to config/app.php

**Comment by travoltron** [comment]
I had already made the change to search but hadn't tagged it yet. I folded in your changes and updated the config. I'll close the PR and issue a new tag.

**Comment by joshstrange** [comment]
@travoltron Just a note:

    'Plaid' => 'Travoltron\Plaid\Plaid::class',

Will cause errors, it doesn't need the quotes around it since it has the ::class on the end. It should be

    'Plaid' => Travoltron\Plaid\Plaid::class,

**Comment by travoltron** [comment]
Fixing now. Haste makes waste, thanks for the catch.

**Comment by travoltron** [comment]
Closed PR since it was attached to first one, which was sorted with tag
1.0.1. Trying to avoid conflicts on that. New PR's are more than welcome.

Thanks for the pickup

On Thu, Jun 16, 2016 at 1:03 PM, Josh Strange <notifications@github.com>
wrote:

> @travoltron <https://github.com/travoltron> Just a note:
>
> 'Plaid' => 'Travoltron\Plaid\Plaid::class',
>
> Will cause errors, it doesn't need the quotes around it since it has the
> ::class on the end. It should be
>
> 'Plaid' => Travoltron\Plaid\Plaid::class,
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/travoltron/plaid/pull/1#issuecomment-226548828>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AChkMuf4ferjo57EMNvQUHwKUv5x6tGDks5qMYH4gaJpZM4I3a2F>
> .
>



-- 
Ben Warburton

**Pull request closed without merging**
